apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node-deployment.yaml
  - node-service.yaml

images:
  - name: carlohcs/kubernetes-ci-cd-github-actions
    # newName: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE
    # newTag: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA